sudo:required
services:
  - docker

before_install:
  - docker build -t 12007158/e-commerce_frontend  -f Dockerfile.dev .

script:
  - docker run 12007158/e-commerce_frontend  npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-552061799873"
  bucket_path: "docker"
  on:
    branch : master
  access_key_id: $Aws_Access_Key
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
